# plotBar.R
# Function for plotting a single Q matrix from Structure or Admixture runs.

#' Generate a barplot of a Structure or Admixture run.
#' @param  cluster_run a single cluster run object of type \code{\link{struct}} or \code{\link{admix}} or data.frame for Q in the same format as that generated by loadAdmixture.
#' @param  populations a data.frame that contains the sample number as the first column and the population as the second.
#' @param  plot if FALSE returns a data.frame for customised plots
#' @param  facet whether or not to split the barplot by cluster. This is recommended.
#' @import ggplot2
#' @importFrom data.table melt
#' @export
#' @examples
#' # Read in Structure files
#' structure_files <- system.file("extdata/microsat_testfiles", package="starmie")
#' structure_output_files <- list.files(structure_files, pattern = "*.out_f", full.names = TRUE)
#' cluster_run <- loadStructure(structure_output_files[[6]])
#' # Generate barplot
#' plotBar(cluster_run)
#'
plotBar <- function(cluster_run, populations=NULL, plot=TRUE, facet=TRUE){

  #i/o checks
  if (!inherits(cluster_run, "struct") & !inherits(cluster_run, "admix") & !inherits(cluster_run, "data.frame")) stop("cluster run must be either a struct or admix object or a Q matrix")
  if (!is.logical(plot)) stop("plot must be one of TRUE or FALSE")

  #Get Q matrix out of object
  if (class(cluster_run)=="struct"){
    Q <- cluster_run$ancest_df[,c(1,3:ncol(cluster_run$ancest_df))]
    Q <- melt(Q, id.vars=c("Label","Pop"), variable.name="Cluster")
    if (!is.null(populations)){
      colnames(populations) <- c("Label", "Family")
      #check the populations match
      if (!setequal(populations$Label, Q$Label)) stop("Mismatch between populations and cluster_run populations.")
      Q <- merge(Q, populations, by.x="Label", by.y="Label")
    } else{
      Q$Family <- Q$Pop
    }
    Q$Pop <- NULL

  } else{
      if (class(cluster_run)=="admix"){
        Q <- cluster_run$Q_df
      } else{
        # we've been given a Q matrix
        if (!all(unlist(apply(cluster_run, 2, is.numeric)))) stop("Columns of Q matrix are not numeric.")
        Q <- cluster_run
      }

      Q$Label <- rownames(Q)
      Q <- melt(Q, id.vars="Label", variable.name="Cluster")

      if (!is.null(populations)){
        colnames(populations) <- c("Label", "Family")
        #check the populations match
        if (!setequal(populations$Label, Q$Label)) stop("Mismatch between populations and cluster_run populations.")
        Q <- merge(Q, populations, by.x="Label", by.y="Label")
      } else{
        Q$Family <- Q$Label
      }
  }

  #Generate plot
  Q <- Q[order(Q$Cluster),]
  gg <- ggplot(Q, aes(x=factor(Label), y=value, fill=factor(Cluster)))
  if (!is.null(populations)){
    if (facet){
      gg <- gg + facet_grid( Cluster ~ Family, scales = "free_x", space = "free_x")
    } else{
      gg <- gg + facet_grid( . ~ Family, scales = "free_x", space = "free_x")
    }
  } else{
    if (facet){
      gg <- gg + facet_grid( Cluster ~ ., scales = "free_x", space = "free_x")
    }
  }
  gg <- gg + geom_bar(stat = "identity", width=1)
  gg <- gg + scale_y_continuous(expand=c(0,0), breaks=c(0.25,0.75))
  gg <- gg + xlab("Sample ID") + ylab("Proportion of cluster")
  gg <- gg + theme_bw()
  gg <- gg + guides(fill=guide_legend(title="Cluster"))
  gg <- gg + theme(axis.text.x = element_text(angle = 90))

  #print plot or return
  if (plot){
    print(gg)
  } else{
    return(Q)
  }

}
