# plotBar.R
# Function for plotting a single Q matrix from Structure or Admixture runs.

#' Generate a barplot of a Structure or Admixture run.
#' @param  cluster_run a single cluster run object of type \code{\link{struct}} or \code{\link{admix}} or data.frame for Q in the same format as that generated by loadAdmixture.
#' @param  populations a data.frame that contains the sample number as the first column and the population as the second.
#' @param  plot if FALSE returns a data.frame for customised plots
#' @param  facet whether or not to split the barplot by cluster. This is recommended.
#' @import ggplot2
#' @importFrom data.table melt
#' @export
#' @examples
#' # Read file using K = 6 and plot results
#' k6_data <- exampleStructure("barplot")
#' print(k6_data)
#' # Generate barplot
#' plotBar(k6_data)
#' # adding group information
#' set.seed(212)
#' pops <- data.frame(id = k6_data$ancest_df[,1],
#' population = sample(letters[1:3], nrow(k6_data$ancest_df), replace = TRUE))
#' # our facetted structure plot
#' plotBar(k6_data, pops)
#' # standard 'structure' bar plot
#' plotBar(k6_data, pops, facet = FALSE)
plotBar <- function(cluster_run, populations=NULL, plot=TRUE, facet=TRUE){

  #i/o checks
  if (!inherits(cluster_run, "struct") & !inherits(cluster_run, "admix") & !inherits(cluster_run, "matrix")) stop("cluster run must be either a struct or admix object or a Q matrix")
  if (!is.logical(plot)) stop("plot must be one of TRUE or FALSE")

  #Get Q matrix out of object
  if (class(cluster_run)=="struct"){
    Q <- getQ(cluster_run)
    #If no population labels are given try to use those available in the structure run.
    if (is.null(populations)) {
      if ("Pop" %in% colnames(cluster_run$ancest_df)){
        populations <- cluster_run$ancest_df[,c(1,3)]
      }
    }
  }
  else if(class(cluster_run)=="admix"){
    Q <- cluster_run$Q_df
  } else{
    Q <- cluster_run
  }

  plot_results <- plotQ(Q, populations, facet)

  if(plot){
    return(plot_results$plot)
  } else{
    return(plot_results$Q_melt)
  }

}

plotQ <- function(Q, populations_df, facet){

  if (is.null(populations_df)){
    #Generate a plot without any family information
    Q_melt <- melt(Q, variable.name="Cluster")
    colnames(Q_melt) <- c("Label", "Cluster", "value")
  } else{
    if (!setequal(populations_df[,1], rownames(Q))) stop("Mismatch between populations and cluster_run populations.")
    colnames(populations_df) <- c("Label", "Population")
    Q_merge <- merge(populations_df, Q, by.x="Label", by.y=0)
    Q_melt <- melt(Q_merge, id.vars=c("Label", "Population"), variable.name="Cluster")
  }

  #Generate plot
  Q_melt <- Q_melt[order(Q_melt$Cluster),]
  gg <- ggplot(Q_melt, aes(x=factor(Label), y=value, fill=factor(Cluster)))
  if (!is.null(populations_df)){
    if (facet){
      gg <- gg + facet_grid( Cluster ~ Population, scales = "free_x", space = "free_x")
    } else{
      gg <- gg + facet_grid( . ~ Population, scales = "free_x", space = "free_x")
    }
  } else{
    if (facet){
      gg <- gg + facet_grid( Cluster ~ ., scales = "free_x", space = "free_x")
    }
  }
  gg <- gg + geom_bar(stat = "identity", width=1)
  gg <- gg + scale_y_continuous(expand=c(0,0), breaks=c(0.25,0.75))
  gg <- gg + xlab("Sample ID") + ylab("Proportion of cluster")
  gg <- gg + theme_bw()
  gg <- gg + guides(fill=guide_legend(title="Cluster"))
  gg <- gg + theme(axis.text.x = element_text(angle = 90))

  #print plot or return
  return(list(Q_melt = Q_melt, plot=gg))
}
